deviceHosts:
  - name: My WiiM Device
    ip: 10.10.10.254

description: >+
  Make a copy of this file and rename it to config.yaml.
  Replace `deviceHosts` with an array of objects. 
  Each object should contain a `name` and an `ip` field. 
  Example of multiple devices:
    - name: WiiM Device A
      ip: 10.10.10.125
    - name: WiiM Device B
      ip: 10.10.10.127
  The IP address of the device can be found in the device's settings > network status.
